### ISSUE TITLE
Send multisig transaction

### ISSUE THREAD

**Issue by meyns** [nemtech/symbol-cli#197]
Is there a way to send a multisig transaction using the nem2-cli?

**Comment by dgarcia360** [comment]
Right now is not possible to start multisig transactions from the nem2-cli, only to cosign them. 

I keep this issue open to discuss about how this functionality could be implemented.

**Comment by decentraliser** [comment]
We could create a multisig flag that could be passed to any transaction
command

If selected, then prompt the user with 2 options:

   1. Get multisig accounts from network
   2. Enter a public key or an address

if option 1 is chosen, we retrieve the multisig children from the network,
and prompt the user with the list of multisig accounts

Le sam. 25 janv. 2020 à 08:35, David Garcia <notifications@github.com> a
écrit :

**Comment by evias** [comment]
+1 on the `--multisig` flag but one that could define the **signer public key**. So maybe my proposal ends up more as `--signer signerPubKey`. 

Because this is something that the CLI could automatically detect. Yet, querying multisig information needs connectivity so please advise/coordinate on how to and *when* to retrieve this information. 

Symbol desktop wallet uses a signer selector principle where **one account** can always initiate transactions:

1) _for itself_
2) or _for any multi-signature account of which it is a cosignatory_

By adding a principle of `signer selector`, it is then easier to detect a _cosignatory mode_ which would always prepare (any kind of) transactions inside a multisig (aggregate bonded).

**Comment by decentraliser** [comment]
After more thought about it, I think that my idea was overkill and that Evias solution is better

An account's cosigners can be retrieved from `symbol-cli account info`, and the view is quite succinct, there is no info about min/max approval/removal, etc
![image](https://user-images.githubusercontent.com/36499647/79177998-a2a0c380-7e36-11ea-98f6-73fc1ad26f6c.png)

I think we should add one more command to get a view of the multisig info of an account's multisig accounts.

**Comment by dgarcia360** [comment]
Closed by #271
