### ISSUE TITLE
Announce transaction with payload

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-cli#210]
`nem2-cli converter payloadToTransaction` command, apart from displaying the transaction content, should ask the users if they want to announce the transaction.

**Comment by meyns** [comment]
Should also add an easy way to extract the payload. I can't find a way to extract just the payload from "nem2-cli transaction transfer"

**Comment by decentraliser** [comment]
you can get the payload easily for each transaction, in the transaction
confirmation screen:

[image: image.png]

**Comment by meyns** [comment]
Maybe this is a problem not for here, but I'm trying to extract just the payload and doing it in batch writing to a txt file, but am unsuccesful.
2 problems: if I extract the payload from the answer it gets mangled with extra binary code (which is fixable with some workarounds). 2nd problem is if I do not want to announce the transaction, I have to enter "n" but am unsuccesful in automating this. Adding a --display or something instead of --announce or --sync would solve this

**Comment by evias** [comment]
I dont agree with the announcement put inside the `converter` responsibility.

Something like `symbol-cli transaction announce --payload ...` would be preferred.
