### ISSUE TITLE
Cosginatures AggregateTransactionComplete not implement

### ISSUE THREAD

**Issue by vlad-bondarenko** [nemtech/symbol-cli#316]
Using latest symbol-sdk-java 0.20.2.
Trying implement logic from https://docs.symbolplatform.com/guides/aggregate/adding-cosginatures-aggregate-complete.html.
This library symbol-sdk-java not support this?

**Comment by dgarcia360** [comment]
Hi @vlad-bondarenko,

This issue tracker is used to report issues for the [Symbol Command Line Interface](https://docs.symbolplatform.com/cli.html), which is a different project than the [Symbol Java SDK](https://github.com/nemtech/symbol-sdk-java).

Since your message looks more like a support question rather than an actual issue with the lib, I'd like to invite you to join our community of developers in [Slack](https://join.slack.com/t/nem2/shared_invite/enQtMzY4MDc2NTg0ODgyLWZmZWRiMjViYTVhZjEzOTA0MzUyMTA1NTA5OWQ0MWUzNTA4NjM5OTJhOGViOTBhNjkxYWVhMWRiZDRkOTE0YmU) and share your question in the #help channel.

**Comment by vlad-bondarenko** [comment]
Exists integration tests for Cosginatures AggregateTransactionComplete?
